### ISSUE TITLE
Habe folgende Fehlermeldung

### ISSUE THREAD

**Issue by Reimai73** [Woersty/LoxBerry-Plugin-Start-LandroidSrv#3]
Hallo,
Habe das Plugin installiert und Loxberry neu gestartet, bekomme aber folgende Fehlermeldung:
An error occured :(...
General error 1: The main template file is not readable. We must abort here, sorry. 

FHEM Plugin und MQTT Gateway Plugin sind installiert
Bitte um Hilfe
Liebe Grüße
Reinhard

**Comment by Woersty** [comment]
Welche Loxberry Version hast du?

**Comment by Reimai73** [comment]
Hab vor ca. 4 Wochen auf 2.(??)neu aufgesetzt.

**Comment by Woersty** [comment]
Ah ich sehe schon. Update kommt nachher

**Comment by Woersty** [comment]
Achso Reinhard, das Loglevel für das Plugin kann man jetzt über die Pluginverwaltung einstellen. Das greift aber nur, wenn du das Plugin nochmal deinstallierst und neu installierst...

**Comment by Reimai73** [comment]
Werde ich gleich einmala machen. Danke schön
